### ISSUE TITLE
No voices on galaxy s6

### ISSUE THREAD

**Issue by zeromz** [tkem/openlap#79]
For some reason I'm finding I can't get vocals working at all. My volume is up so I have no idea why I'm having this issue. I have English set as my default language.

**Comment by zeromz** [comment]
Worked when I reloaded the app, sorry.

**Comment by tkem** [comment]
No problem. If your phone is set to the same language as the app, this *should* work without restarting the app. Only if languages differ, speech support files may have to be downloaded by Android in the background, which may take some time and would explain the described behavior.
